# 上下文初始化加载
info:
  name: Eureka Server
  contact: Eureka 服务器

management:
  security:
    enabled: false
     
spring:
  profiles:
    active: dev
    
#启用shutdown
endpoints:
  shutdown:
    enabled: true
    #禁用密码验证
    sensitive: false
    
---
spring:
  profiles: dev
server:
  port: 8761
eureka:
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉取信息
    fetchRegistry: false
    # eureka server地址
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
  instance:
    hostname: ${HOSTNAME:localhost}
---
spring:
  profiles: prod
  cloud:
    client:
      hostname: ${HOSTNAME:localhost}
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka_service_url}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: true
    # 服务剔除任务执行周期
    evictionIntervalTimerInMs: 60000
    # 服务端缓存最长时间
    responseCacheUpdateIntervalMs: 30000
  instance:
    hostname: ${INSTANCE_HOSTNAME}